/* ------------------------------------------------------------------
 * characters/公共.js —— 全角色通用的「动作中文名」表
 *
 * 动作名是官方统一命名（Pat_Idle 在所有角色身上都是"被摸头"），
 * 所以这张表对所有角色通用。角色文件里可以再写自己的 animLabel 覆盖它。
 * 由 03_工具\批量生成角色文件.js 生成。
 * ------------------------------------------------------------------ */
const ANIM_LABEL_COMMON = {
 "Angry_1": "生气 1",
 "Angry_2": "生气 2",
 "Angry_3": "生气 3",
 "Angry_4": "生气 4",
 "Angry_5": "生气 5",
 "Close_1": "闭眼 1",
 "Eat_1": "吃东西 1",
 "Eat_2": "吃东西 2",
 "Happy_1": "开心 1",
 "Happy_2": "开心 2",
 "Happy_3": "开心 3",
 "Happy_4": "开心 4",
 "Happy_5": "开心 5",
 "Happy_6": "开心 6",
 "Idle_1": "待机",
 "Idle_2": "待机 2",
 "Idle_3": "待机 3",
 "Ignore_1": "无视 1",
 "Ignore_2": "无视 2",
 "Pat_End": "摸头结束",
 "Pat_Idle": "被摸头",
 "Sad_1": "难过 1",
 "Sad_2": "难过 2",
 "Sad_3": "难过 3",
 "Sad_4": "难过 4",
 "Sleep_1": "睡觉 1",
 "Smash_End_1": "敲头·敲下去",
 "Smash_End_2": "敲头·哭了",
 "Sorry_1": "道歉 1",
 "Sulky_1": "闹别扭 1",
 "Sulky_2": "闹别扭 2",
 "Surprise_1": "惊讶 1",
 "Surprise_2": "惊讶 2",
 "Surprise_3": "惊讶 3",
 "Surprise_4": "惊讶 4",
 "Talk_1": "说话 1",
 "Taunt_1": "挑衅 1",
 "Taunt_2": "挑衅 2",
 "Taunt_3": "挑衅 3",
 "Taunt_4": "挑衅 4",
 "Tickle_End": "摸肚子·大笑收尾",
 "Tickle_Idle_1": "摸肚子·开始",
 "Tickle_Idle_2": "摸肚子·笑不停",
 "Touch_End": "捏脸结束",
 "Touch_Idle": "被捏脸",
 "Track_1": "跟随镜头 1",
 "Aside_1": "坨格形态 1",
 "Aside_2": "坨格形态 2",
 "Spawn_1": "登场 1",
 "Upgrade_1": "升级 1",
 "Upgrade_2": "升级 2",
 "Angry_6": "生气 6",
 "Angry_7": "生气 7",
 "Angry_8": "生气 8",
 "Blank_1": "无表情 1",
 "Blank_2": "无表情 2",
 "Blank_3": "无表情 3",
 "Dance_1": "跳舞 1",
 "Panic_1": "慌张 1",
 "Panic_2": "慌张 2",
 "Sad_5": "难过 5",
 "Sad_6": "难过 6",
 "Sleep_2": "睡觉 2",
 "Tired_1": "疲倦 1",
 "Serious_1": "认真 1",
 "Serious_2": "认真 2",
 "Serious_3": "认真 3",
 "Serious_4": "认真 4",
 "Shy_1": "害羞 1",
 "Shy_2": "害羞 2",
 "Shy_3": "害羞 3",
 "Shy_4": "害羞 4",
 "Shy_5": "害羞 5",
 "Shy_6": "害羞 6",
 "Shy_7": "害羞 7",
 "Sulky_3": "闹别扭 3",
 "Act_1_1": "动作 1-1",
 "Act_2_1": "动作 2-1",
 "Act_3_1": "动作 3-1",
 "Angry1_1": "生气",
 "Eat1_1": "吃东西",
 "Idle": "待机",
 "Move": "移动",
 "Play1_1": "玩耍",
 "Sleep1_1": "睡觉",
 "Spawn": "登场",
 "Swim1_1": "游泳",
 "Angry_9": "生气 9",
 "Angry_10": "生气 10",
 "Close_2": "闭眼 2",
 "Dance_2": "跳舞 2",
 "Dance_3": "跳舞 3",
 "Happy_7": "开心 7",
 "Panic_3": "慌张 3",
 "Robot_1": "机器人 1",
 "Robot_2": "机器人 2",
 "Robot_3": "机器人 3",
 "Robot_4": "机器人 4",
 "Sad_7": "难过 7",
 "Sad_8": "难过 8",
 "Sad_9": "难过 9",
 "Scary_1": "吓人 1",
 "Scary_2": "吓人 2",
 "Scary_3": "吓人 3",
 "Scary_4": "吓人 4",
 "Blank_4": "无表情 4",
 "Eat_3": "吃东西 3",
 "Eat_4": "吃东西 4",
 "Happy_8": "开心 8",
 "Idle_4": "待机 4",
 "Panic_4": "慌张 4",
 "Pride_1": "骄傲 1",
 "Pride_2": "骄傲 2",
 "Pride_3": "骄傲 3",
 "Pride_4": "骄傲 4",
 "Spit_1": "吐东西 1",
 "Spit_2": "吐东西 2",
 "Dance_4": "跳舞 4",
 "Drink_1": "喝东西 1",
 "Drink_2": "喝东西 2",
 "Drink_3": "喝东西 3",
 "Hi_1": "打招呼 1",
 "Hi_2": "打招呼 2",
 "Rhythm_1": "打拍子 1",
 "Rhythm_2": "打拍子 2",
 "Rhythm_3": "打拍子 3",
 "Sorry_2": "道歉 2",
 "Surprise_5": "惊讶 5",
 "Talk_2": "说话 2",
 "Talk_3": "说话 3",
 "Dizzy_1": "晕乎乎 1",
 "Dizzy_2": "晕乎乎 2",
 "Loudspeaker_1": "扩音器 1",
 "Loudspeaker_2": "扩音器 2",
 "Loudspeaker_3": "扩音器 3",
 "Merong_1": "吐舌头 1",
 "Merong_2": "吐舌头 2",
 "Merong_3": "吐舌头 3",
 "Disgust_1": "嫌弃 1",
 "Happy_9": "开心 9",
 "Happy_10": "开心 10",
 "Panic_5": "慌张 5",
 "Panic_6": "慌张 6",
 "Serious_5": "认真 5",
 "Serious_6": "认真 6",
 "Yoga_1": "瑜伽 1",
 "Yoga_2": "瑜伽 2",
 "Blank_5": "无表情 5",
 "Notmyfault_1": "不是我的错 1",
 "Notmyfault_2": "不是我的错 2",
 "Notmyfault_3": "不是我的错 3",
 "Bread_1": "面包 1",
 "Bread_2": "面包 2",
 "Bread_3": "面包 3",
 "Bread_4": "面包 4",
 "Magic_1": "魔法 1",
 "Magic_2": "魔法 2",
 "Magic_3": "魔法 3",
 "Thinking_1": "思考 1",
 "Thinking_2": "思考 2",
 "Cute_1": "卖萌 1",
 "Cute_2": "卖萌 2",
 "Cute_3": "卖萌 3",
 "Heart_1": "爱心 1",
 "Heart_2": "爱心 2",
 "Heart_3": "爱心 3",
 "Heart_4": "爱心 4",
 "Lying_1": "躺下 1",
 "Lying_2": "躺下 2",
 "Lying_3": "躺下 3",
 "Lying_4": "躺下 4",
 "Lying_5": "躺下 5",
 "Lying_6": "躺下 6",
 "Lying_7": "躺下 7",
 "Mad_1": "发火 1",
 "Mad_2": "发火 2",
 "Mad_3": "发火 3",
 "Groggy_1": "晕眩 1",
 "Lazy_1": "懒洋洋 1",
 "Lazy_2": "懒洋洋 2",
 "Lazy_3": "懒洋洋 3",
 "Lazy_4": "懒洋洋 4",
 "Glasses_1": "眼镜 1",
 "Glasses_2": "眼镜 2",
 "Glasses_3": "眼镜 3",
 "Glasses_4": "眼镜 4",
 "Help_1": "求助 1",
 "Help_2": "求助 2",
 "Think_1": "思考 1",
 "Act_1": "动作 1",
 "Act_2": "动作 2",
 "Act_3": "动作 3",
 "Act_4": "动作 4",
 "Act_5": "动作 5",
 "Act_6": "动作 6",
 "Worry_1": "担心 1",
 "Worry_2": "担心 2",
 "Eat_5": "吃东西 5",
 "Eat_6": "吃东西 6",
 "Eat_7": "吃东西 7",
 "Eat_8": "吃东西 8",
 "Excited_1": "兴奋 1",
 "Excited_2": "兴奋 2",
 "Excited_3": "兴奋 3",
 "Proud_1": "得意 1",
 "Proud_2": "得意 2",
 "Sleepy_1": "犯困 1",
 "Sleepy_2": "犯困 2",
 "Sorry_3": "道歉 3",
 "Thinking_3": "思考 3",
 "Thinking_4": "思考 4",
 "Thinking_5": "思考 5",
 "Greeting_1": "打招呼 1",
 "Greeting_2": "打招呼 2",
 "Posing_1": "摆姿势 1",
 "Posing_2": "摆姿势 2",
 "Smell_1": "闻一闻 1",
 "Act1_1": "动作 1",
 "Act2_1": "动作 2",
 "Act3_1": "动作 3",
 "Aside_3": "坨格形态 3",
 "Point_1": "指 1",
 "Point_2": "指 2",
 "Oioi_1": "喂喂 1",
 "Oioi_2": "喂喂 2",
 "Sleepy": "犯困",
 "Latte_1": "拿铁 1",
 "Latte_2": "拿铁 2",
 "Open_1": "睁眼 1",
 "Open_2": "睁眼 2",
 "Open_3": "睁眼 3",
 "Open_4": "睁眼 4",
 "Open_5": "睁眼 5",
 "Open_6": "睁眼 6",
 "Regret_1": "后悔 1",
 "Regret_2": "后悔 2",
 "Regret_3": "后悔 3",
 "Sulky_4": "闹别扭 4",
 "Idle_5": "待机 5",
 "Mad_4": "发火 4",
 "Mad_5": "发火 5",
 "Panic_7": "慌张 7",
 "Ban_1": "禁止 1",
 "Fear_1": "害怕 1",
 "Off_1": "关闭 1",
 "Sleep_3": "睡觉 3",
 "Sad_10": "难过 10",
 "Sad_11": "难过 11",
 "Walk_1": "走路 1",
 "Walk_2": "走路 2",
 "Joke_1": "开玩笑 1",
 "Joke_2": "开玩笑 2",
 "Joke_3": "开玩笑 3",
 "Money_1": "钱 1",
 "Money_2": "钱 2",
 "Sneaky_1": "偷偷摸摸 1",
 "Sneaky_2": "偷偷摸摸 2",
 "Sneaky_3": "偷偷摸摸 3",
 "Sneaky_4": "偷偷摸摸 4",
 "Talk_4": "说话 4",
 "Talk_5": "说话 5",
 "Talk_6": "说话 6",
 "Talk_7": "说话 7",
 "Angry_11": "生气 11",
 "Angry_12": "生气 12",
 "Angry_13": "生气 13",
 "Angry_14": "生气 14",
 "Angry_15": "生气 15",
 "Angry_16": "生气 16",
 "Bbang_1": "砰 1",
 "Blank_6": "无表情 6",
 "Blank_7": "无表情 7",
 "Blank_8": "无表情 8",
 "Eat_9": "吃东西 9",
 "Eat_10": "吃东西 10",
 "Eat_11": "吃东西 11",
 "Happy_11": "开心 11",
 "Happy_12": "开心 12",
 "Happy_13": "开心 13",
 "Happy_14": "开心 14",
 "Happy_15": "开心 15",
 "Happy_16": "开心 16",
 "Happy_17": "开心 17",
 "Happy_18": "开心 18",
 "Happy_19": "开心 19",
 "Hungry_1": "肚子饿 1",
 "Hungry_2": "肚子饿 2",
 "Hungry_3": "肚子饿 3",
 "Notmyfault_4": "不是我的错 4",
 "Ottokhaji _1": "怎么办 1",
 "Present_1": "送礼 1",
 "Present_2": "送礼 2",
 "Present_3": "送礼 3",
 "Sad_12": "难过 12",
 "Sad_13": "难过 13",
 "Sad_14": "难过 14",
 "Sad_15": "难过 15",
 "Sad_16": "难过 16",
 "Sad_17": "难过 17",
 "Surprise_6": "惊讶 6",
 "Surprise_7": "惊讶 7",
 "Angry_17": "生气 17",
 "Blank_9": "无表情 9",
 "Blank_10": "无表情 10",
 "Blank_11": "无表情 11",
 "Cheeky_1": "调皮 1",
 "Cheeky_2": "调皮 2",
 "Hit_1": "受击 1",
 "Hit_2": "受击 2",
 "Hungry_4": "肚子饿 4",
 "Question_1": "疑问 1",
 "Question_2": "疑问 2",
 "Go_1": "上吧 1",
 "Go_2": "上吧 2",
 "Rock_1": "石头 1",
 "Rock_2": "石头 2",
 "Rock_3": "石头 3",
 "Sulky_5": "闹别扭 5",
 "Hesitate_1": "犹豫 1",
 "Hesitate_2": "犹豫 2",
 "Nodding_1": "点头 1",
 "Nodding_2": "点头 2",
 "Nodding_3": "点头 3",
 "Point_3": "指 3",
 "Surprised_1": "惊讶 1",
 "Surprised_2": "惊讶 2",
 "Dumb_1": "哑口无言 1",
 "Dumb_2": "哑口无言 2",
 "Sword_1": "剑 1",
 "Sword_2": "剑 2",
 "Sword_3": "剑 3",
 "Sword_4": "剑 4",
 "Sword_5": "剑 5",
 "Sword_6": "剑 6",
 "Camera_1": "相机 1",
 "Camera_2": "相机 2",
 "Camera_3": "相机 3",
 "Camera_4": "相机 4",
 "Camera_5": "相机 5",
 "Camera_6": "相机 6",
 "Camera_7": "相机 7",
 "Clock_1": "时钟 1",
 "Clock_2": "时钟 2",
 "Note_1": "便签 1",
 "Note_2": "便签 2",
 "Note_3": "便签 3",
 "Nope_1": "才不要 1",
 "Nope_2": "才不要 2",
 "Nope_3": "才不要 3",
 "Mask_1": "面具 1",
 "Scroll_1": "卷轴 1",
 "Scroll_2": "卷轴 2",
 "Scroll_3": "卷轴 3",
 "Scroll_4": "卷轴 4",
 "Scroll_5": "卷轴 5",
 "Sitting_1": "坐着 1",
 "Sitting_2": "坐着 2",
 "Sitting_3": "坐着 3",
 "Sitting_4": "坐着 4",
 "Sitting_5": "坐着 5",
 "Special_1": "特殊 1",
 "Special_2": "特殊 2",
 "Special_3": "特殊 3",
 "Special_4": "特殊 4",
 "Laugh_1": "大笑 1",
 "Laugh_2": "大笑 2",
 "Smile_1": "微笑 1",
 "Close_3": "闭眼 3",
 "Pray_1": "祈祷 1",
 "Pray_2": "祈祷 2",
 "Pray_3": "祈祷 3",
 "Sorry_4": "道歉 4",
 "Tired_2": "疲倦 2",
 "Tired_3": "疲倦 3",
 "Shock_1": "震惊 1",
 "Shock_2": "震惊 2",
 "Shock_3": "震惊 3",
 "Sleepy_3": "犯困 3",
 "Hug_1": "拥抱 1",
 "Stop_1": "停 1",
 "Mic_1": "麦克风 1",
 "Mic_2": "麦克风 2",
 "Mic_3": "麦克风 3",
 "Promise_1": "约定 1",
 "Promise_2": "约定 2",
 "Track_2": "跟随镜头 2",
 "Track_3": "跟随镜头 3",
 "Why_1": "为什么 1",
 "Why_2": "为什么 2",
 "Melong_1": "吐舌头 1",
 "Melong_2": "吐舌头 2",
 "Melong_3": "吐舌头 3",
 "Scream_1": "尖叫 1",
 "Relaxed_1": "放松 1",
 "Relaxed_2": "放松 2",
 "Think_2": "思考 2",
 "Nicesmile_1": "灿烂笑容 1",
 "Pose_1": "摆姿势 1",
 "Salute_1": "敬礼 1",
 "Tired_4": "疲倦 4",
 "Tired_5": "疲倦 5",
 "Mad_6": "发火 6",
 "Laser_1": "激光 1",
 "Laser_2": "激光 2",
 "Laser_3": "激光 3",
 "Laser_4": "激光 4",
 "Laser_5": "激光 5",
 "Quiet_1": "安静 1",
 "Smile_2": "微笑 2",
 "Note_4": "便签 4",
 "Panic_8": "慌张 8",
 "Warning_1": "警告 1",
 "Smash": "敲头",
 "Calm_1": "平静 1",
 "Calm_2": "平静 2",
 "Calm_3": "平静 3",
 "Calm_4": "平静 4",
 "Curious_1": "好奇 1",
 "Curious_2": "好奇 2",
 "Curious_3": "好奇 3",
 "Curious_4": "好奇 4",
 "Shame_1": "羞耻 1",
 "Smirking_1": "坏笑 1",
 "Smirking_2": "坏笑 2",
 "Beam_1": "光束 1",
 "Singing_1": "唱歌 1",
 "Singing_2": "唱歌 2",
 "Singing_3": "唱歌 3",
 "Mirror_1": "镜子 1",
 "Mirror_2": "镜子 2",
 "Mirror_3": "镜子 3",
 "Mirror_4": "镜子 4",
 "Mirror_5": "镜子 5",
 "Shame_2": "羞耻 2",
 "Mad_7": "发火 7",
 "Pray_4": "祈祷 4",
 "Pray_5": "祈祷 5",
 "Check_1": "检查 1",
 "Check_2": "检查 2",
 "Check_3": "检查 3",
 "Drill_1": "钻 1",
 "Drill_2": "钻 2",
 "Drill_3": "钻 3",
 "Concent_1": "专注 1",
 "Concent_2": "专注 2",
 "Recorder_1": "录音机 1",
 "Recorder_2": "录音机 2",
 "Recorder_3": "录音机 3",
 "Sweat_1": "冒汗 1",
 "Sweat_2": "冒汗 2",
 "Work_1": "工作 1",
 "Work_2": "工作 2",
 "Work_3": "工作 3",
 "Work_4": "工作 4",
 "Proud_3": "得意 3",
 "V_1": "V 手势 1",
 "V_2": "V 手势 2",
 "Salute_2": "敬礼 2",
 "Salute_3": "敬礼 3",
 "Salute_4": "敬礼 4",
 "Salute_5": "敬礼 5",
 "Speak_1": "说话 1",
 "Speak_2": "说话 2",
 "Speak_3": "说话 3",
 "Succession_1": "连招 1",
 "Succession_2": "连招 2",
 "Groggy_2": "晕眩 2",
 "Clap_1": "拍手 1",
 "Clap_2": "拍手 2",
 "Clap_3": "拍手 3",
 "Clap_4": "拍手 4",
 "Cook_1": "做饭 1",
 "Cook_2": "做饭 2",
 "Cook_3": "做饭 3",
 "Cook_4": "做饭 4",
 "Cook_5": "做饭 5",
 "Groggy_3": "晕眩 3",
 "Laugh_3": "大笑 3",
 "Laugh_4": "大笑 4",
 "Laugh_5": "大笑 5",
 "TIckle": "摸肚子",
 "Scouter_1": "探测镜 1",
 "Scouter_2": "探测镜 2",
 "Scouter_3": "探测镜 3",
 "Scouter_4": "探测镜 4",
 "Call_1": "呼唤 1",
 "Call_2": "呼唤 2",
 "Call_3": "呼唤 3",
 "Call_4": "呼唤 4",
 "Call_5": "呼唤 5",
 "Shame_3": "羞耻 3",
 "Taunt_5": "挑衅 5",
 "Attack_1": "攻击 1",
 "Fight_1": "战斗 1",
 "Fight_2": "战斗 2",
 "Fight_3": "战斗 3",
 "Fight_4": "战斗 4",
 "Recoder_1": "录音机 1",
 "Recoder_2": "录音机 2",
 "Serious_7": "认真 7",
 "Serious_8": "认真 8",
 "Sit_1": "坐下 1",
 "Sit_2": "坐下 2",
 "Sit_3": "坐下 3",
 "Sit_4": "坐下 4",
 "Tease_1": "逗弄 1",
 "Tease_2": "逗弄 2",
 "Squat_1": "蹲下 1",
 "Strong_1": "强硬 1",
 "Strong_2": "强硬 2",
 "Strong_3": "强硬 3",
 "Strong_4": "强硬 4",
 "Strong_5": "强硬 5",
 "Villain_1": "反派 1",
 "Villain_2": "反派 2",
 "Villain_3": "反派 3",
 "Villain_4": "反派 4",
 "Villain_5": "反派 5",
 "Villain_6": "反派 6",
 "Quiet_2": "安静 2",
 "Think_3": "思考 3",
 "Whisper_1": "悄悄话 1",
 "Whisper_2": "悄悄话 2",
 "Wink_1": "眨眼 1",
 "Joke_4": "开玩笑 4",
 "Annoy_1": "烦躁 1",
 "Annoy_2": "烦躁 2",
 "Annoy_3": "烦躁 3",
 "Annoy_4": "烦躁 4",
 "Dizzy_3": "晕乎乎 3",
 "Fear_2": "害怕 2",
 "Fear_3": "害怕 3",
 "Fear_4": "害怕 4",
 "Splash_1": "水花 1",
 "Splash_2": "水花 2",
 "Splash_3": "水花 3",
 "Splash_4": "水花 4",
 "Splash_5": "水花 5",
 "Read_1": "阅读 1",
 "Read_2": "阅读 2",
 "Read_3": "阅读 3",
 "Write_1": "写字 1",
 "Write_2": "写字 2",
 "Write_3": "写字 3",
 "Write_4": "写字 4",
 "Write_5": "写字 5",
 "Break_1": "破坏 1",
 "Break_2": "破坏 2",
 "Dash_1": "冲刺 1",
 "Dash_2": "冲刺 2",
 "Dash_3": "冲刺 3",
 "Drift_1": "漂移 1",
 "Drift_2": "漂移 2",
 "Drift_3": "漂移 3",
 "Drive_1": "驾驶 1",
 "Drive_2": "驾驶 2",
 "Drive_3": "驾驶 3",
 "Smile_3": "微笑 3",
 "Dere_1": "娇羞 1",
 "EasterEgg_Happy_1": "彩蛋·开心 1",
 "Pistol_1": "手枪 1",
 "Pistol_2": "手枪 2",
 "Pistol_3": "手枪 3",
 "Revolver_1": "左轮 1",
 "Revolver_2": "左轮 2",
 "Revolver_3": "左轮 3",
 "Rummage_1": "翻找 1",
 "Rummage_2": "翻找 2",
 "Rummage_3": "翻找 3",
 "Rummage_4": "翻找 4",
 "No_1": "摇头 1",
 "No_2": "摇头 2",
 "Yes_1": "点头 1",
 "Yes_2": "点头 2",
 "Knee_1": "跪下 1",
 "Parrot_1": "鹦鹉 1",
 "Touch": "被捏脸",
 "Clean_1": "打扫 1",
 "Clean_2": "打扫 2",
 "Clean_3": "打扫 3",
 "Stand_1": "站立 1",
 "Stand_2": "站立 2",
 "Stand_3": "站立 3",
 "Boring_1": "无聊 1",
 "Phone_1": "手机 1",
 "Phone_2": "手机 2",
 "Phone_3": "手机 3",
 "Phone_4": "手机 4",
 "Doubt_1": "疑惑 1",
 "Doubt_2": "疑惑 2",
 "Ouch_1": "好疼 1",
 "Ouch_2": "好疼 2",
 "Sword_7": "剑 7",
 "Sword_8": "剑 8",
 "Sword_9": "剑 9",
 "Sword_10": "剑 10",
 "Jump_1": "跳 1",
 "Sing_1": "唱歌 1",
 "Sing_2": "唱歌 2",
 "Close_4": "闭眼 4",
 "Cool_1": "耍帅 1",
 "Cool_2": "耍帅 2",
 "Aiming_1": "瞄准 1",
 "Closed_1": "闭眼 1",
 "Idle1": "待机",
 "Idle01": "待机",
 "Ultimate": "必杀技",
 "Die": "倒下",
 "Victory": "胜利",
 "Defeat": "失败",
 "Hit": "受击",
 "Attack": "攻击",
 "Skill": "技能",
 "Upgrade": "升级",
 "Aside": "坨格形态",
 "Blank": "无表情",
 "Track": "跟随镜头",
 "Close": "闭眼",
 "Closed": "闭眼",
 "Open": "睁眼",
 "Happy": "开心",
 "Proud": "得意",
 "Pride": "骄傲",
 "Angry": "生气",
 "Sad": "难过",
 "Surprise": "惊讶",
 "Surprised": "惊讶",
 "Dizzy": "晕乎乎",
 "Panic": "慌张",
 "Taunt": "挑衅",
 "Serious": "认真",
 "Shy": "害羞",
 "Sulky": "闹别扭",
 "Sorry": "道歉",
 "Regret": "后悔",
 "Smile": "微笑",
 "Smirking": "坏笑",
 "Laugh": "大笑",
 "Fear": "害怕",
 "Shock": "震惊",
 "Disgust": "嫌弃",
 "Curious": "好奇",
 "Calm": "平静",
 "Relaxed": "放松",
 "Groggy": "晕眩",
 "Excited": "兴奋",
 "Worry": "担心",
 "Doubt": "疑惑",
 "Annoy": "烦躁",
 "Mad": "发火",
 "Dere": "娇羞",
 "Boring": "无聊",
 "Shame": "羞耻",
 "Hungry": "肚子饿",
 "Tired": "疲倦",
 "Sleep": "睡觉",
 "Lazy": "懒洋洋",
 "Quiet": "安静",
 "Cool": "耍帅",
 "Cute": "卖萌",
 "Nicesmile": "灿烂笑容",
 "Cheeky": "调皮",
 "Sneaky": "偷偷摸摸",
 "Hesitate": "犹豫",
 "Sweat": "冒汗",
 "Ouch": "好疼",
 "Scream": "尖叫",
 "Ignore": "无视",
 "Think": "思考",
 "Thinking": "思考",
 "Nope": "才不要",
 "No": "摇头",
 "Yes": "点头",
 "Nodding": "点头",
 "Why": "为什么",
 "Question": "疑问",
 "Promise": "约定",
 "Help": "求助",
 "Stop": "停",
 "Warning": "警告",
 "Ban": "禁止",
 "Off": "关闭",
 "Go": "上吧",
 "Greeting": "打招呼",
 "Hi": "打招呼",
 "Jump": "跳",
 "Squat": "蹲下",
 "Wink": "眨眼",
 "Hug": "拥抱",
 "Tease": "逗弄",
 "Whisper": "悄悄话",
 "Speak": "说话",
 "Talk": "说话",
 "Sing": "唱歌",
 "Singing": "唱歌",
 "Clap": "拍手",
 "Point": "指",
 "Present": "送礼",
 "Pray": "祈祷",
 "Check": "检查",
 "Read": "阅读",
 "Write": "写字",
 "Work": "工作",
 "Clean": "打扫",
 "Cook": "做饭",
 "Drink": "喝东西",
 "Eat": "吃东西",
 "Dance": "跳舞",
 "Yoga": "瑜伽",
 "Walk": "走路",
 "Dash": "冲刺",
 "Drift": "漂移",
 "Drive": "驾驶",
 "Stand": "站立",
 "Sit": "坐下",
 "Sitting": "坐着",
 "Lying": "躺下",
 "Knee": "跪下",
 "Pose": "摆姿势",
 "Posing": "摆姿势",
 "Salute": "敬礼",
 "Fight": "战斗",
 "Aiming": "瞄准",
 "Pistol": "手枪",
 "Revolver": "左轮",
 "Sword": "剑",
 "Laser": "激光",
 "Beam": "光束",
 "Magic": "魔法",
 "Drill": "钻",
 "Rock": "石头",
 "Strong": "强硬",
 "Break": "破坏",
 "Succession": "连招",
 "Rhythm": "打拍子",
 "Recorder": "录音机",
 "Recoder": "录音机",
 "Mic": "麦克风",
 "Loudspeaker": "扩音器",
 "Phone": "手机",
 "Camera": "相机",
 "Mirror": "镜子",
 "Scouter": "探测镜",
 "Glasses": "眼镜",
 "Mask": "面具",
 "Clock": "时钟",
 "Note": "便签",
 "Scroll": "卷轴",
 "Bread": "面包",
 "Money": "钱",
 "Rummage": "翻找",
 "Spit": "吐东西",
 "Splash": "水花",
 "Swim": "游泳",
 "Call": "呼唤",
 "Heart": "爱心",
 "Notmyfault": "不是我的错",
 "Melong": "吐舌头",
 "Merong": "吐舌头",
 "Robot": "机器人",
 "Villain": "反派",
 "Scary": "吓人",
 "Special": "特殊",
 "EasterEgg_Happy": "彩蛋·开心",
 "Concent": "专注",
 "Drum": "打鼓",
 "Drumming": "打鼓",
 "Joke": "开玩笑",
 "Act": "动作",
 "Tickle": "摸肚子",
 "V": "V 手势",
 "Dumb": "哑口无言",
 "Smell": "闻一闻",
 "Parrot": "鹦鹉",
 "Latte": "拿铁",
 "Bbang": "砰",
 "Ottokhaji": "怎么办",
 "Oioi": "喂喂"
};
